[SAD-27] Clicking Start All button on Manage Modules page display a grammatically incorrect message
openmrs/openmrs-owa-sysadmin pull request #18
Opened 2018-12-04 17:26 UTC by JyothsnaAshok

## Description of what I changed

The start all modules refers to all the modules and hence modules' would be appropriate to use.

## Issue I worked on

Issue: https://issues.openmrs.org/browse/SAD-27
Task instance: [Task](https://codein.withgoogle.com/dashboard/task-instances/4793954353545216/)

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2018-12-04 18:07 UTC, bwolfe commented on app/js/moduleView/moduleViewControllers.js
> +                    $scope.startAllModuleSuccess = "Action completed successfully. Please check the modules' status";
Or would adding just the word "each" make it easier to understand?
```suggestion
                    $scope.startAllModuleSuccess = "Action completed successfully. Please check each module's status";
```

2018-12-05 12:25 UTC, suthagar23 requested changes

2018-12-05 12:25 UTC, suthagar23 commented on app/js/moduleView/moduleViewControllers.js
> +                    $scope.startAllModuleSuccess = "Action completed successfully. Please check the modules' status";
Yes, It will add more value to the message. @JyothsnaAshok Can you change it accordingly?

2018-12-06 03:10 UTC, suthagar23 approved these changes

2018-12-06 03:10 UTC, merged